### ISSUE TITLE
bulk transfer failed : LIBUSB_ERROR_TIMEOUT

### ISSUE THREAD

**Issue by Achref-Dachraoui** [OpenThermal/libseek-thermal#24]
Hi, 

I'm using libseek on Raspberry Pi and it runs perfectly. However, there is an issue that appears after running seek_viewer.cpp or seek_test_pro.cpp with seek compact pro and an extensible OTG cable :

     Error : bulk transfer failed : LIBUSB_ERROR_TIMEOUT
     Error : frame acquisition failed
     Failed to read frame from camera, existing 

I can't figure out if the issue come from the software side of the driver or from the hardware (ex : the quality of the OTG cable i'm using) 

Can you please help me resolving this issue? 
Thank you in advance for your answer !

**Comment by maartenvds** [comment]
Sorry for late reply. I guess it's the usb cable. In my experience, not all cabled work well.
