### ISSUE TITLE
Failed to open seek cam

### ISSUE THREAD

**Issue by Aifuding** [OpenThermal/libseek-thermal#31]
Elite,can't  open the cam
./seek_test_pro -> Error: first grab failed    failed to open seek cam
help,help..

**Comment by pauledd** [comment]
Do you see the cam id via:
`lsusb`
?

**Comment by Aifuding** [comment]
yes,  lsusb
Bus 001 Device 002: ID 289d:0011

**Comment by Aifuding** [comment]
running on VMware

**Comment by pauledd** [comment]
you could try to run seek_test_pro as root... If that works than you need to set up the udev rules...

**Comment by Aifuding** [comment]
$ sudo ./seek_test_pro 
Error: first grab failed
failed to open seek cam
Connection method : seek thermal->usb->VMware->lsusb, What can be affected?

**Comment by pauledd** [comment]
I have no idea, I run my Seek Pro via qemu without problems on emulated windows... Cant help with VMware

**Comment by Aifuding** [comment]
Thank you very much for your kind attention personal response

**Comment by tejesh002** [comment]
Error: libusb init failed: LIBUSB_ERROR_ACCESS
