### ISSUE TITLE
Error: control transfer failed: LIBUSB_ERROR_PIPE

### ISSUE THREAD

**Issue by vitcozzolino** [OpenThermal/libseek-thermal#33]
I have compiled and installed the library (and followed all required configuration steps) but I'm not able to run the tests. This is the output I see when running `seek_test`:

```
Error: control transfer failed: LIBUSB_ERROR_PIPE
Error: control transfer failed: LIBUSB_ERROR_PIPE
Error: control transfer failed: LIBUSB_ERROR_PIPE
Error: control transfer failed: LIBUSB_ERROR_PIPE
Error: control transfer failed: LIBUSB_ERROR_PIPE
Error: init_cam failed
Error accessing camera
Error: control transfer failed: LIBUSB_ERROR_PIPE
Error: control transfer failed: LIBUSB_ERROR_PIPE
Error: control transfer failed: LIBUSB_ERROR_PIPE

```
Any ideas what could be the issue? I had a look at the code and checked the type of error, it seems that the init commands sent to the camera are not correct. I'm using a SeekThermal CompactXR and running on Ubuntu 18.04

**Comment by katzdave** [comment]
Same issue for me, running on Ubuntu 16.04

**Comment by jmiseikis** [comment]
Did you find a workaround for this issue..? I'm facing a similar issue with Seek Compact Pro and Ubuntu 18.04.

Camera works well if started within a few seconds of plugging in, but results in this error if started later after plugging the camera to the USB (10 secs or later).

**Comment by simpart** [comment]
i had the same issue on raspberrypi3.
so i connected another USB port as a workaround.

**Comment by jmiseikis** [comment]
My colleague helped me to find a workaround. Apparently the camera went to auto suspend mode and could not be started. Disabling USB auto suspend on Ubuntu helped to get the camera running successfully in all the cases. Guide: https://askubuntu.com/questions/1140925/how-can-i-disable-usb-autosuspend-on-ubuntu-18-04
