### ISSUE TITLE
seek_viewer Fullscreen output

### ISSUE THREAD

**Issue by kristofbremen** [OpenThermal/libseek-thermal#34]
Hi,

it would be great to show the output in fullscreen, how can this be realized?

Regards
Kristof

**Comment by SciProj-LDN** [comment]
@kristofbremen Narco post I know but if you're still trying to do this you can change the opencv calls in the seek viewer you're using to tell it to set the window to fullscreen.

**Comment by Bostwickenator** [comment]
Done!
