### ISSUE TITLE
Shutter information

### ISSUE THREAD

**Issue by etienenD** [OpenThermal/libseek-thermal#38]
Hi everyone, 

I would like to know if it's possible to modify the shutter settings and how. 

I saw on the SeekDevice.h file 3 device commands: 
- GET_SHUTTER_POLARITY
- SET_SHUTTER_POLARITY
- TOGGLE_SHUTTER

But I don't know what these commands do and how to use it.

Is there anyone to tell me more about the shutter settings ? 
Because when I stream the video, the image freeze during shutter event and thoses events come out very often.

Thank you in advance all.

Etienne

**Comment by Bostwickenator** [comment]
From my research I am pretty certain this is not possible on the current cameras. I suspect it was possible on the first versions of the Seek Compact. Configuring out the shutter now causes the camera to reset.
