### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by power-max** [OpenThermal/libseek-thermal#40]
going back one directory with `cd ..` following the cmake command is necessary.
Corrected instructions (that worked for me at least)
```
cd libseek-thermal
mkdir build
cd build
cmake ../
cd ..
make
```

**Comment by maartenvds** [comment]
Not sure what you did, but normally the makefile will be generated in the build folder with those commands so you have to run make inside the build folder. What environment do you use, what version of cmake?

**Comment by power-max** [comment]
I will have to go back and report back what version. I am on KDE Neon using the latest software in the repos.
