### ISSUE TITLE
Can I use this code for Seek shot pro?

### ISSUE THREAD

**Issue by darlcode** [OpenThermal/libseek-thermal#41]
Hi :) 

I have some questions about this code!
I know this code for seek compact series.
But I wanna know there is a way to connect seek shot pro and stream in real time with this code..!

Thank you for reading :)

**Comment by Bostwickenator** [comment]
Check the examples folder to show how to view the video.

**Comment by ash2703** [comment]
It is still not clear, can the code be used for seek shot pro

**Comment by Bostwickenator** [comment]
This implements a USB interface to for the Seek **Compact** devices. It is not compatible with the Seek Shot series.

**Comment by ash2703** [comment]
> This implements a USB interface to for the Seek **Compact** devices. It is not compatible with the Seek Shot series.

Is there any API which supports seek shot pro series

**Comment by Bostwickenator** [comment]
Not that I am aware of sorry.
