### ISSUE TITLE
v4l2 support

### ISSUE THREAD

**Issue by hex0r** [OpenThermal/libseek-thermal#56]
Hi everyone,

I try to stream thermal imaging data using gstreamer without success

try to setup v4l2 loopback:
seek_viewer --camtype=seekpro --colormap=11 --mode=v4l2 --output=/dev/video0

then using the following gstreamer pipe:
gst-launch-1.0 v4l2src device=/dev/video0 ! video/x-raw,width=320,height=240,framerate=15/1 ! omxh264enc control-rate=1 target-bitrate=600000 interval-intraframes=1 periodicty-idr=1 ! h264parse config-interval=3 ! rtph264pay ! udpsink host=127.0.0.1 port=5600

get this error :
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0: Internal data stream error.
Additional debug info:
gstbasesrc.c(3055): gst_base_src_loop (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
streaming stopped, reason not-negotiated (-4)
Execution ended after 0:00:00.003602959
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...

please could anybody give me a hand 
thx

I have the following setup:
***  raspi4 
***  seek thermal pro

**Comment by Bostwickenator** [comment]
Very late reply I know but did you get this working?
