### ISSUE TITLE
libseek-thermal shows a camera sensor defect, but official Android app doesn't. [SOLVED]

### ISSUE THREAD

**Issue by bum112** [OpenThermal/libseek-thermal#64]
I have Seek Thermal CompactPRO. I have tested the camera with libseek-thermal and official Android app. The image returned from libseek-thermal looks like camera itself has sensor defect in the bottom, however, Android app doesn't show any defect. I inspected the problem for a very long time in different conditions. I don't think, that Android app uses very advanced AI image repair. I have attached the video comparison.

https://user-images.githubusercontent.com/80056442/110252035-2b16de00-7f8c-11eb-8c96-5cbe8cef2cb7.mp4

What is going on?

**Comment by Bostwickenator** [comment]
Very interesting I haven't seen that before on either of my devices. You could attempt to skip the dead pixel filtering and see what happens. See https://github.com/OpenThermal/libseek-thermal/blob/master/src/SeekCam.cpp#L272
just change the body of the function to be `src.copyTo(dst);`. If that changes the result you could either leave it out for your camera or adjust the thresholding functions https://github.com/OpenThermal/libseek-thermal/blob/master/src/SeekCam.cpp#L243

**Comment by bum112** [comment]
Holly shit! It actually worked. Thank you! I used the first suggestion.
Could you please add this option in the code, so other people can also use it. I am very big noob.

Just now I have one dead (stuck on white) pixel, but I guess it would be possible to remove that by using your second suggestion.
