### ISSUE TITLE
Doesn't recognize OpenCV ColorMap ID

### ISSUE THREAD

**Issue by Neshtek** [OpenThermal/libseek-thermal#74]
I'm working on a Raspberry Pi 4 Model B.
When I run the seek_viewer command with colormap id > 12 it throws an error that tells me to enter an ID that is valid.

Command:
`seek_viewer --camtype=seek --colormap=14`

Error:
```
OpenCV Error: Bad argument (Unknown colormap id; use one of COLORMAP_*) in applyColorMap, file /build/opencv-L65chJ/opencv-3.2.0+dfsg/modules/imgproc/src/colormap.cpp, line 543
terminate called after throwing an instance of 'cv::Exception'
what():  /build/opencv-L65chJ/opencv-3.2.0+dfsg/modules/imgproc/src/colormap.cpp:543: error: (-5) Unknown colormap id; use one of COLORMAP_* in function applyColorMap

Aborted
```

**Comment by Bostwickenator** [comment]
Make sure you build against a version of OpenCV which has 14 color maps if you want to use 14 color maps. See the OpenCV documentation here https://docs.opencv.org/4.x/d3/d50/group__imgproc__colormap.html use the dropdown to select your version of OpenCV and see the list of valid color maps.
